
[build]
  publish = "website"

[[redirects]]
  from = "/*"
  to = "https://main-street-marketplace.streamlit.app"
  status = 301
  force = true
  conditions = {Host = ["app.mainstreetmarketplace.org"]}